--- 
script: nosetests
after_script: 
- test $TRAVIS_BRANCH = master && bash pkg/build-ubuntu-upstart.sh && travis-artifacts upload --path *.deb --target-path /
env: 
  global: 
  - ARTIFACTS_S3_BUCKET: gilliam-artifacts
  - secure: |-
      O1l6Ma20Il0bqgCSUkEq42a3yIS61JUT9/nUkFqi+MRzSkzN6pZT9L3H4E1l
      dJ3l7zlgqK7oqtMnZeng696sfPwGClggHGkLfHDTyylScm0soiJPqky5q1Eq
      LTD8a4HgR+YPTsPT26L3VNwSDJmOdXnid29H2mwILGuGS7ZN32Q=
  - secure: |-
      eK/raUtZx2iQJQJLKyMS+drpjptYF0IHChjiM54+nhtMjyUBVduHGIk3M8Mp
      oHDj8iOm6gMoXQmOn/dyNmjlbMT4G+CWUMMLu6Det+s3F0lVIXm9tb9qgdJc
      j0vI1gnhw5FvqzGOGcyb8gNiAqFGUppMGEFtcVjeopAg1WjZPWA=
before_script: 
- gem install travis-artifacts
- gem install fpm
services: sqlite3
install: pip install -r requirements.txt --use-mirrors
before_install: 
- pip install --use-mirrors Cython
language: python
python: 
- "2.7"
