--- 
env: 
  global: 
  - ARTIFACTS_S3_BUCKET: gilliam-artifacts
  - secure: |-
      KyjwvwFNay+XgrhjkxDy1yu+kcwiby3A7VzkyYcmeP280ikUFUjdpz9YjFMH
      Vn8EvCV+dMYWnP9lEdn37iYJVg7OSTuIjjimNfEyJSo0cTFQPMYfocjeNkhe
      8VB1v/XNFVeTKkGYcS5ptp22xEcKS/3BBdcfhOPIZEcrtUct4YQ=
  - secure: |-
      CpViBJr3N3HhtTq9YsKQB4OjeaZn27O4Y7l8JlUTkflFWDMC9sLnSA4UMV0J
      Yb67fdP66h+nSI7cM6+9toe99qtWamjV8iFjjQrS4sHv/tgH9CGEQ1sdDsnX
      2kD19zpCRrmbnf6Xcr/3mNEoax2mAzkEMQaogjm1a3Qm5+cAOs8=
python: 
- "2.7"
services: sqlite3
install: pip install -r requirements.txt --use-mirrors
after_script: 
- test $TRAVIS_BRANCH = master && bash pkg/build-ubuntu-upstart.sh && travis-artifacts upload --path *.deb --target-path /
language: python
script: nosetests
before_install: 
- pip install --use-mirrors Cython
before_script: 
- gem install travis-artifacts
- gem install fpm
